<a href="https://colab.research.google.com/github/MaxHoefl/Blog/blob/master/pytorch_playground.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip3 install torch torchvision

    100% |████████████████████████████████| 519.5MB 31kB/s 
tcmalloc: large alloc 1073750016 bytes == 0x5965a000 @  0x7fb840e542a4 0x594e17 0x626104 0x51190a 0x4f5277 0x510c78 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f6070 0x510c78 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f6070 0x4f3338 0x510fb0 0x5119bd 0x4f6070
    100% |████████████████████████████████| 61kB 21.0MB/s 
    100% |████████████████████████████████| 2.0MB 4.3MB/s 
  Found existing installation: Pillow 4.0.0
    Uninstalling Pillow-4.0.0:
      Successfully uninstalled Pillow-4.0.0


In [0]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision

In [0]:
%matplotlib inline
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
from pprint import pprint

In [0]:
from IPython.core.debugger import set_trace

### Torch tensors

In [13]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [14]:
torch.rand(3,5)

tensor([[0.4810, 0.0693, 0.9426, 0.8425, 0.1018],
        [0.1980, 0.0057, 0.7171, 0.5056, 0.4294],
        [0.2367, 0.2671, 0.3231, 0.0311, 0.1749]])

In [17]:
X = torch.rand(5,3)
Y = torch.rand(5,3)
X.t() @ Y # matrix multiplication

tensor([[1.2628, 1.1545, 0.6890],
        [1.5474, 1.5828, 0.8876],
        [0.7205, 0.8192, 0.5650]])

In [18]:
X.add_(1) # inplace operation

tensor([[1.7042, 1.0899, 1.3819],
        [1.2071, 1.6515, 1.4357],
        [1.8332, 1.6914, 1.2213],
        [1.5940, 1.6898, 1.2829],
        [1.3474, 1.9797, 1.5156]])

In [21]:
X.numpy() # torch -> numpy

array([[1.7042485, 1.0899212, 1.3819463],
       [1.2071315, 1.6514671, 1.4357421],
       [1.8331538, 1.6913891, 1.2212812],
       [1.5939865, 1.6897602, 1.2829142],
       [1.347432 , 1.9796572, 1.5155935]], dtype=float32)

In [22]:
torch.from_numpy(np.eye(3)) # numpy -> torch

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], dtype=torch.float64)

## Autograd

In [0]:
from torch import autograd

In [27]:
w = torch.ones(1) 
z = torch.ones(1)

z.requires_grad, w.requires_grad # by default no gradients are computed

(False, False)

In [0]:
total = w**2 + z**2

In [29]:
total.backward() # THROWS ERROR because we didnt register w and z in the computational graph in order

RuntimeError: ignored

In [0]:
w = torch.ones(1, requires_grad=True)
z = torch.ones(1, requires_grad=True)
total = w**2 + z**2
total.backward() # automatic differentiate total with respect to w and z (and evaluate gradients at current values of w and z)

In [34]:
w.grad, z.grad # evaluate the gradients

(tensor([2.]), tensor([2.]))

## Running on device

In [0]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [11]:
device

device(type='cuda', index=0)